import Head from "next/head";
import Link from "next/link";
import React from "react";

export default function Home() {
  const [data, setData] = React.useState(null);

  return (
    <>
      <Head>
        <title>Next App - About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1>Nextjs: About Page</h1>
        <Link href="/">Back to Home</Link>
      </main>
    </>
  );
}
