import Footer from "@/components/footer";
import Header from "@/components/header";
import Main from "@/components/main";
import Head from "next/head";
import Link from "next/link";
import React from "react";

export default function Home() {
  // const [data, setData] = React.useState(null);

  // React.useEffect(() => {
  //   const externalSourceUrl = "https://jsonplaceholder.typicode.com/todos/1";
  //   const nextApiUrl = "http://localhost:3100/api/hello";
  //   const coreApiUrl = "http://mzee.ir:82/api/WeatherForecast";
  //   fetch(coreApiUrl).then(async (res) => {
  //     const data = await res.json();
  //     setData(data);
  //   });
  // }, []);

  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='horizontal-flow-content'>
        <Header />
        <Main />
        <Footer />
      </main>
    </>
  );
}
